# allow queries with date range up to the longest month (31 days):
DEFAULT_PATIENT_APPOINTMENTS_INFO_REQUEST_DATE_PARAMS_MAX_DELTA_IN_DAYS = 30
DEFAULT_FINANCING_SOURCE_INFO_REQUEST_DATE_PARAMS_MAX_DELTA_IN_DAYS = 30
