# Generated by Django 3.2.7 on 2021-10-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("start_at", models.DateTimeField(db_column="begDate")),
                ("executed_at", models.DateTimeField(db_column="endDate")),
            ],
            options={
                "db_table": "Action",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ActionType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_column="name", max_length=512)),
            ],
            options={
                "db_table": "ActionType",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(db_column="firstName", max_length=30)),
                ("patr_name", models.CharField(db_column="patrName", max_length=30)),
                ("last_name", models.CharField(db_column="lastName", max_length=120)),
            ],
            options={
                "db_table": "Person",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("start_at", models.DateTimeField(db_column="setDate")),
                ("executed_at", models.DateTimeField(db_column="execDate")),
            ],
            options={
                "db_table": "Event",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EventType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_column="name", max_length=64)),
            ],
            options={
                "db_table": "EventType",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FinancingSource",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_column="name", max_length=64)),
            ],
            options={
                "db_table": "rbFinance",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Organisation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(db_column="fullName", max_length=636)),
            ],
            options={
                "db_table": "Organisation",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OrganisationStructure",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_column="name", max_length=256)),
            ],
            options={
                "db_table": "OrgStructure",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(db_column="firstName", max_length=30)),
                ("patr_name", models.CharField(db_column="patrName", max_length=64)),
                ("last_name", models.CharField(db_column="lastName", max_length=30)),
            ],
            options={
                "db_table": "Client",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "Visit",
                "abstract": False,
                "managed": False,
            },
        ),
    ]
