# Generated by Django 3.2.7 on 2021-12-09 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_patronymic'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationGis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=150)),
                ('gis_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('gis_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organizationgis')),
            ],
        ),
    ]
