# Generated by Django 3.2.7 on 2021-12-07 14:27

from django.db import migrations


def add_organizations_gis_id(apps, schema_editor):
    organization_gis = apps.get_model("core", "OrganizationGis")
    organization_gis.objects.create(org_name="Больница", gis_id=5489290326838114)
    organization_gis.objects.create(
        org_name="Амбулаторно-поликлиническое туберкулезное отделение", gis_id=5489290326974357
    )
    organization_gis.objects.create(org_name="Приемное отделение", gis_id=70000001029928623)
    organization_gis.objects.create(org_name="Инфекционное отделение", gis_id=70000001029928664)
    organization_gis.objects.create(org_name="Хирургическое отделение №1", gis_id=70000001029928685)
    organization_gis.objects.create(org_name="Травматологическое отделение", gis_id=70000001029928696)
    organization_gis.objects.create(org_name="Оториноларингологическое отделение", gis_id=70000001029928700)
    organization_gis.objects.create(org_name="Педиатрическое отделение", gis_id=70000001029928728)
    organization_gis.objects.create(org_name="Акушерское отделение", gis_id=70000001020349605)
    organization_gis.objects.create(org_name="Клинико-диагностическая лаборатория", gis_id=70000001054375272)
    organization_gis.objects.create(org_name="Педиатрическое отделение", gis_id=70000001020350525)
    organization_gis.objects.create(org_name="Терапевтическое отделение", gis_id=70000001029928633)
    organization_gis.objects.create(org_name="Кардиологическое отделение", gis_id=70000001029928640)
    organization_gis.objects.create(org_name="Гастроэнтерологическое отделение", gis_id=70000001029928644)
    organization_gis.objects.create(org_name="Пульмонологическое отделение", gis_id=70000001029928650)
    organization_gis.objects.create(org_name="Неврологическое отделение", gis_id=70000001029928658)
    organization_gis.objects.create(org_name="Психиатрическое отделение", gis_id=70000001029928670)
    organization_gis.objects.create(org_name="Наркологическое отделение", gis_id=70000001029928675)
    organization_gis.objects.create(org_name="Отделение анестезиологии и реанимации", gis_id=70000001029928679)
    organization_gis.objects.create(org_name="Отделение гнойной хирургии", gis_id=70000001029928690)
    organization_gis.objects.create(org_name="Гинекологическое отделение", gis_id=70000001029928715)
    organization_gis.objects.create(org_name="Родильное отделение", gis_id=70000001029928738)
    organization_gis.objects.create(org_name="Отделение новорожденных детей", gis_id=70000001029928749)
    organization_gis.objects.create(org_name="Эндоскопическое отделение", gis_id=70000001029928760)
    organization_gis.objects.create(org_name="Отделение ультразвуковой диагностики", gis_id=70000001029928764)
    organization_gis.objects.create(org_name="Рентгеновское отделение", gis_id=70000001029928770)
    organization_gis.objects.create(org_name="Отделение функциональной диагностики", gis_id=70000001029928773)
    organization_gis.objects.create(org_name="Отделение медицинской реабилитации", gis_id=70000001029928776)
    organization_gis.objects.create(org_name="Патологоанатомическое отделение", gis_id=70000001029928785)
    organization_gis.objects.create(org_name="Отделение клинической эпидемиологии", gis_id=70000001045669336)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_organizationgis_review"),
    ]

    operations = [
        migrations.RunPython(add_organizations_gis_id),
    ]
